### ISSUE TITLE
[JsonConfig] Cannot parse json5 config! 

### ISSUE THREAD

**Issue by stoffel7** [crycode-de/ioBroker.ds18b20#117]
error message when open configuration of adapter:
[JsonConfig] Cannot parse json5 config! 
adapter cannot configured(search for sensors)
see discussion:
[https://forum.iobroker.net/topic/75516/jsonconfig-cannot-parse-json5-config](url)

Browser console log:
`fetch http://10.10.13.80:8081/validate_config/ds18b20
console.ts:40 [JsonConfig] Cannot parse json5 config!
console.ts:40 TypeError: Cannot read properties of null (reading '#include')
    at ms.scanForInclude (JsonConfig.tsx:392:20)
    at ms.scanForInclude (JsonConfig.tsx:405:44)
    at ms.scanForInclude (JsonConfig.tsx:405:44)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms._getConfigFile (JsonConfig.tsx:463:17)
console.ts:40 fetch http://10.10.13.80:8081/validate_config/ds18b20
console.ts:40 [JsonConfig] Cannot parse json5 config!
console.ts:40 TypeError: Cannot read properties of null (reading '#include')
    at ms.scanForInclude (JsonConfig.tsx:392:20)
    at ms.scanForInclude (JsonConfig.tsx:405:44)
    at ms.scanForInclude (JsonConfig.tsx:405:44)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms.scanForInclude (JsonConfig.tsx:405:27)
    at async ms._getConfigFile (JsonConfig.tsx:463:17)`
![DS18B20](https://github.com/crycode-de/ioBroker.ds18b20/assets/39948331/8e2de4b2-c766-4f94-a621-01e7734d9790)

**Comment by crycode-de** [comment]
Thanks for reporting this issue!

Seems like it's related to Admin >= 6.17.0.
I'll check this.

**Comment by crycode-de** [comment]
As previously suspected it's a bug in the admin adapter. I've created an issue and PR to fix this.

Current workaround is to downgrade admin to some version before 6.17.0.

**Comment by JoeKN82** [comment]
I'm having the same issue. Downgrading the ioBroker admin to a version before 6.17.0 doesn't seem to help. However, downgrading the ds18b20 adapter to a version below 2 does resolve the problem.

In my case, the ds18b20 adapter is running on a Raspberry Pi (on an ioBroker slave instance). Could this be impacting the issue?

**Comment by crycode-de** [comment]
@JoeKN82 Downgrading the adapter to some version below 2 is NOT recommended, because it changes some internals and uses the very outdated old config and an outdated config format which might not be compatible with any current adapter version.

You may try to use the latest beta release of the admin adapter (currently 7.0.11) wich has this issue fixed.

Keep in mind, that on a multihost install you need to have the correct admin version installed at the master.
